In [10]:
import dash
import dash_core_components as dcc
import dash_html_components as html
import pandas as pd
import plotly.graph_objs as go
from dash.dependencies import Input, Output

In [11]:
app = dash.Dash()
server = app.server

In [12]:
df = pd.read_csv("stock_data.csv ")
df2 = pd.read_csv("dataset_Facebook.csv ",";")

In [13]:
df

,Date,Open,High,Low,Close,Volume,OpenInt,Stock
0,1984-09-07,0.42388,0.42902,0.41874,0.42388,23220030,0,AAPL
1,1984-09-10,0.42388,0.42516,0.41366,0.42134,18022532,0,AAPL
2,1984-09-11,0.42516,0.43668,0.42516,0.42902,42498199,0,AAPL
3,1984-09-12,0.42902,0.43157,0.41618,0.41618,37125801,0,AAPL
4,1984-09-13,0.43927,0.44052,0.43927,0.43927,57822062,0,AAPL
5,1984-09-14,0.44052,0.45589,0.44052,0.44566,68847968,0,AAPL
6,1984-09-17,0.45718,0.46357,0.45718,0.45718,53755262,0,AAPL
7,1984-09-18,0.45718,0.46103,0.44052,0.44052,27136886,0,AAPL
8,1984-09-19,0.44052,0.44566,0.43157,0.43157,29641922,0,AAPL
9,1984-09-20,0.43286,0.43668,0.43286,0.43286,18453585,0,AAPL
10,1984-09-21,0.43286,0.44566,0.42388,0.42902,27842780,0,AAPL
11,1984-09-24,0.42902,0.43157,0.42516,0.42516,22033109,0,AAPL
12,1984-09-25,0.42388,0.42388,0.41618,0.41618,46515020,0,AAPL
13,1984-09-26,0.41618,0.43540,0.41111,0.41111,30947546,0,AAPL
14,1984-09-27,0.41111,0.41366,0.41111,0.41111,29541971,0,AAPL
15,1984-09-28,0.41111,0.41111,0.39316,0.40081,65093531,0,AAPL
16,1984-10-01,0.39956,0.39956,0.39186,0.39186,27268068,0,AAPL
17,1984-10-02,0.39443,0.40853,0.39443,0.39443,32977801,0,AAPL
18,1984-10-03,0.40081,0.40724,0.40081,0.40081,33583772,0,AAPL
19,1984-10-04,0.40593,0.40853,0.40593,0.40593,34995586,0,AAPL
20,1984-10-05,0.40593,0.40593,0.39443,0.39699,27211851,0,AAPL
21,1984-10-08,0.39699,0.39956,0.39699,0.39699,13099922,0,AAPL
22,1984-10-09,0.39699,0.39956,0.39316,0.39316,34933112,0,AAPL
23,1984-10-10,0.39316,0.39316,0.38164,0.38164,101750813,0,AAPL
24,1984-10-11,0.38164,0.39186,0.37906,0.37906,50969114,0,AAPL
25,1984-10-12,0.37906,0.38164,0.35985,0.36241,74126674,0,AAPL
26,1984-10-15,0.38289,0.38674,0.38289,0.38289,67842205,0,AAPL
27,1984-10-16,0.38289,0.38419,0.38164,0.38164,32915346,0,AAPL
28,1984-10-17,0.39699,0.39956,0.39699,0.39699,43685142,0,AAPL
29,1984-10-18,0.40853,0.41111,0.40853,0.40853,68929180,0,AAPL
...,...,...,...,...,...,...,...,...
19556,2017-10-02,171.39000,171.87000,168.75000,169.47000,13368468,0,FB
19557,2017-10-03,169.30000,170.73000,169.20000,169.96000,8178289,0,FB
19558,2017-10-04,169.83000,170.67000,168.29000,168.42000,11928425,0,FB
19559,2017-10-05,169.18000,171.31000,168.60000,171.24000,14559033,0,FB
19560,2017-10-06,170.25000,172.37000,169.75000,172.23000,13100116,0,FB
19561,2017-10-09,172.70000,174.88000,172.00000,172.50000,14554019,0,FB
19562,2017-10-10,173.00000,173.20000,170.80000,171.59000,11332200,0,FB
19563,2017-10-11,171.95000,172.78000,171.40000,172.74000,11253620,0,FB
19564,2017-10-12,172.61000,173.85000,172.29000,172.55000,10462623,0,FB
19565,2017-10-13,173.45000,174.65000,173.20000,173.74000,13618464,0,FB
19566,2017-10-16,174.49000,175.00000,174.06000,174.52000,11457286,0,FB
19567,2017-10-17,174.71000,176.13000,174.36000,176.11000,15927764,0,FB
19568,2017-10-18,176.65000,176.74000,175.75000,176.03000,12725340,0,FB
19569,2017-10-19,174.93000,176.03000,172.63000,174.56000,13879954,0,FB
19570,2017-10-20,175.50000,175.88000,174.63000,174.98000,12430136,0,FB
19571,2017-10-23,175.20000,175.34000,171.25000,171.27000,13831283,0,FB
19572,2017-10-24,172.30000,173.24000,171.50000,171.80000,12167771,0,FB
19573,2017-10-25,171.90000,172.25000,168.89000,170.60000,15862430,0,FB
19574,2017-10-26,171.38000,172.28500,170.39000,170.63000,11714814,0,FB
19575,2017-10-27,174.15000,178.21000,173.90000,177.88000,30269321,0,FB
19576,2017-10-30,179.26000,180.69000,177.61000,179.87000,24353160,0,FB
19577,2017-10-31,180.57000,180.80000,178.94000,180.06000,20174231,0,FB
19578,2017-11-01,182.36000,182.90000,180.57000,182.66000,40918341,0,FB
19579,2017-11-02,180.63000,181.94000,177.34000,178.92000,35529893,0,FB
19580,2017-11-03,179.29000,179.86000,176.71000,178.92000,17822131,0,FB
19581,2017-11-06,178.56000,180.45000,178.31000,180.17000,13275578,0,FB
19582,2017-11-07,180.50000,180.74800,179.40300,180.25000,12903836,0,FB
19583,2017-11-08,179.79000,180.35000,179.11000,179.56000,10467606,0,FB
19584,2017-11-09,178.31000,179.40000,177.09000,179.30000,12602188,0,FB
19585,2017-11-10,178.35000,179.10000,177.96000,178.46000,11060355,0,FB

In [14]:
df2

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
5,139441,Status,2,12,1,9,0.0,10472,20849,1191,1073,1389,16034,7852,1016,1,152.0,33.0,186
6,139441,Photo,3,12,1,3,1.0,11692,19479,481,265,364,15432,9328,379,3,249.0,27.0,279
7,139441,Photo,3,12,7,9,1.0,13720,24137,537,232,305,19728,11056,422,0,325.0,14.0,339
8,139441,Status,2,12,7,3,0.0,11844,22538,1530,1407,1692,15220,7912,1250,0,161.0,31.0,192
9,139441,Photo,3,12,6,10,0.0,4694,8668,280,183,250,4309,2324,199,3,113.0,26.0,142
10,139441,Status,2,12,5,10,0.0,21744,42334,4258,4100,4540,37849,18952,3798,0,233.0,19.0,252
11,139441,Photo,2,12,5,10,0.0,3112,5590,208,127,145,3887,2174,165,0,88.0,18.0,106
12,139441,Photo,2,12,5,10,0.0,2847,5133,193,115,133,3779,2072,152,0,90.0,14.0,104
13,139441,Photo,2,12,5,3,0.0,2549,4896,249,134,168,3631,1917,183,5,137.0,10.0,152
14,138414,Photo,2,12,4,5,1.0,22784,39941,887,337,417,34415,19312,684,2,577.0,20.0,599
15,138414,Status,2,12,3,10,0.0,10060,19680,1264,1209,1425,17272,8548,1162,4,86.0,18.0,108
16,138414,Photo,3,12,3,3,0.0,1722,2981,163,123,148,1868,1050,123,2,40.0,12.0,54
17,138414,Photo,1,12,2,12,1.0,53264,111785,1706,1103,1655,92512,39776,1307,15,678.0,20.0,713
18,138414,Status,3,12,2,3,0.0,3930,7509,130,86,112,5009,2410,101,4,54.0,17.0,75
19,138414,Photo,3,12,1,11,0.0,1591,2825,121,88,111,2116,1161,100,0,34.0,8.0,42
20,138414,Photo,2,12,1,3,0.0,2848,5066,200,142,184,3561,1963,157,3,66.0,12.0,81
21,138414,Photo,1,12,7,10,0.0,1384,2467,15,15,20,2196,1172,15,0,0.0,0.0,0
22,138414,Link,1,12,7,10,0.0,3454,6853,118,104,130,6282,3100,106,0,16.0,2.0,18
23,138414,Photo,3,12,7,3,0.0,2723,4888,176,118,143,2964,1621,143,0,72.0,24.0,96
24,138414,Status,2,12,6,10,0.0,8488,15294,1341,1270,1489,9684,5244,995,3,99.0,19.0,121
25,138458,Status,2,12,6,3,0.0,8284,15104,1521,1462,1711,10266,5372,1200,0,88.0,18.0,106
26,138458,Status,2,12,5,11,0.0,19552,34143,2806,2531,3420,17748,9824,1779,10,412.0,72.0,494
27,138458,Photo,3,12,5,3,0.0,2478,4306,212,124,149,2612,1443,166,0,100.0,17.0,117
28,138895,Photo,2,12,5,3,0.0,9560,18264,973,559,885,9217,4748,621,36,523.0,63.0,622
29,138895,Video,1,12,4,11,1.0,36208,61262,1141,1068,1728,30131,14112,559,18,143.0,13.0,174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
470,91437,Link,1,2,3,13,0.0,9356,14986,448,381,505,13919,8460,392,4,114.0,13.0,131
471,91330,Photo,3,2,3,3,0.0,7732,13264,1066,1002,1336,8753,4880,570,7,160.0,57.0,224
472,91223,Photo,1,2,2,13,0.0,5240,8893,857,837,1020,7420,4232,466,0,46.0,15.0,61
473,91116,Photo,3,2,2,4,1.0,7132,12060,1004,944,1226,8294,4736,576,4,136.0,42.0,182
474,91009,Photo,1,2,1,12,0.0,21928,39641,1512,1479,1837,6338,3672,497,0,73.0,13.0,86
475,86909,Photo,3,1,6,16,1.0,5754,9238,1179,1143,1452,6101,3546,420,0,65.0,19.0,84
476,86909,Photo,1,1,6,10,1.0,37088,10966,2728,2288,3183,66311,34352,2021,7,579.0,47.0,633
477,86909,Link,1,1,6,4,0.0,39600,7927,572,496,581,12522,8176,167,1,101.0,5.0,107
478,86909,Photo,3,1,5,13,0.0,5536,8745,1141,1099,1461,5225,3098,483,1,74.0,31.0,106
479,86909,Photo,3,1,5,4,0.0,6056,10325,1117,1078,1427,6823,3788,487,7,84.0,36.0,127
480,86909,Photo,2,1,4,11,0.0,11484,20696,1762,1635,2741,8774,5124,722,56,360.0,99.0,515
481,86491,Link,1,1,4,4,1.0,4938,7910,66,63,70,6625,3804,59,0,5.0,2.0,7
482,86491,Photo,3,1,3,10,0.0,66784,9456,2969,2833,3645,17809,11328,801,3,187.0,36.0,226
483,86491,Photo,2,1,3,3,0.0,5526,8779,1096,1058,1399,5732,3412,453,2,69.0,26.0,97
484,86491,Photo,3,1,2,7,0.0,5040,8367,1062,1023,1348,5485,3068,437,2,82.0,24.0,108
485,86491,Link,1,1,2,2,0.0,5168,8371,66,59,71,7041,3996,58,0,12.0,2.0,14
486,85979,Photo,3,1,1,12,0.0,5034,8030,1020,993,1243,5340,3094,440,2,56.0,25.0,83
487,85979,Photo,3,1,1,2,0.0,4908,7491,957,937,1153,4642,2842,393,1,44.0,21.0,66
488,85979,Photo,3,1,7,10,0.0,9700,17442,1407,1271,2007,8872,4876,660,21,277.0,80.0,378
489,85979,Photo,3,1,7,2,0.0,4800,7754,975,938,1278,4932,2820,432,1,74.0,28.0,103
490,85979,Photo,3,1,6,11,0.0,5280,8703,951,911,1237,5757,3300,431,1,79.0,30.0,110
491,85979,Photo,3,1,6,3,1.0,6184,10228,956,901,1140,6085,3502,437,1,105.0,46.0,152
492,85979,Link,1,1,5,11,0.0,45920,5808,753,655,763,15766,10720,220,0,128.0,9.0,137
493,85093,Photo,3,1,1,2,0.0,8412,13960,1179,1111,1632,8632,5348,699,17,185.0,55.0,257
494,85093,Photo,3,1,7,10,0.0,5400,9218,810,756,1003,5654,3230,422,10,125.0,41.0,176
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [15]:
app.layout = html.Div([
    # Setting the main title of the Dashboard
    html.H1("Facebook Data Analysis", style={"textAlign": "center"}),
    # Dividing the dashboard in tabs
    dcc.Tabs(id="tabs", children=[
        # Defining the layout of the first Tab
        dcc.Tab(label='Stock Prices', children=[
            html.Div([
                html.H1("Facebook Stocks High vs Lows", 
                        style={'textAlign': 'center'}),
                # Adding the first dropdown menu and the subsequent time-series graph
                dcc.Dropdown(id='my-dropdown',
                             options=[{'label': 'Tesla', 'value': 'TSLA'},
                                      {'label': 'Apple','value': 'AAPL'}, 
                                      {'label': 'Facebook', 'value': 'FB'}, 
                                      {'label': 'Microsoft','value': 'MSFT'}], 
                             multi=True,value=['FB'],
                             style={"display": "block", "margin-left": "auto", 
                                    "margin-right": "auto", "width": "60%"}),
                dcc.Graph(id='highlow'),
                html.H1("Facebook Market Volume", style={'textAlign': 'center'}),
                # Adding the second dropdown menu and the subsequent time-series graph
                dcc.Dropdown(id='my-dropdown2',
                             options=[{'label': 'Tesla', 'value': 'TSLA'},
                                      {'label': 'Apple','value': 'AAPL'}, 
                                      {'label': 'Facebook', 'value': 'FB'},
                                      {'label': 'Microsoft','value': 'MSFT'}], 
                             multi=True,value=['FB'],
                             style={"display": "block", "margin-left": "auto", 
                                    "margin-right": "auto", "width": "60%"}),
                dcc.Graph(id='volume')
            ], className="container"),
        ]),
        # Defining the layout of the second tab
        dcc.Tab(label='Performance Metrics', children=[
            html.H1("Facebook Metrics Distributions", 
                    style={"textAlign": "center"}),
            # Adding a dropdown menu and the subsequent histogram graph
            html.Div([
                      html.Div([dcc.Dropdown(id='feature-selected1',
                      options=[{'label': i.title(),
                                'value': i} for i in df2.columns.values[1:]], 
                                 value="Type")],
                                 className="twelve columns", 
                                 style={"display": "block", "margin-left": "auto",
                                        "margin-right": "auto", "width": "60%"}),
                    ], className="row",
                    style={"padding": 50, "width": "60%", 
                           "margin-left": "auto", "margin-right": "auto"}),
                    dcc.Graph(id='my-graph2'),
        ])
    ])
])

In [19]:
@app.callback(Output('highlow', 'figure'),
              [Input('my-dropdown', 'value')])
def update_graph(selected_dropdown):
    dropdown = {"TSLA": "Tesla","AAPL": "Apple","FB": "Facebook","MSFT": "Microsoft",}
    trace1 = []
    trace2 = []
    for stock in selected_dropdown:
        trace1.append(
          go.Scatter(x=df[df["Stock"] == stock]["Date"],
                     y=df[df["Stock"] == stock]["High"],
                     mode='lines', opacity=0.7, 
                     name=f'High {dropdown[stock]}',textposition='bottom center'))
        trace2.append(
          go.Scatter(x=df[df["Stock"] == stock]["Date"],
                     y=df[df["Stock"] == stock]["Low"],
                     mode='lines', opacity=0.6,
                     name=f'Low {dropdown[stock]}',textposition='bottom center'))
    traces = [trace1, trace2]
    data = [val for sublist in traces for val in sublist]
    figure = {'data': data,
              'layout': go.Layout(colorway=["#5E0DAC", '#FF4F00', '#375CB1', 
                                            '#FF7400', '#FFF400', '#FF0056'],
            height=600,
            title=f"High and Low Prices for Over Time",
            xaxis={"title":"Date",
                   'rangeselector': {'buttons': list([{'count': 1, 'label': '1M', 
                                                       'step': 'month', 
                                                       'stepmode': 'backward'},
                                                      {'count': 6, 'label': '6M', 
                                                       'step': 'month', 
                                                       'stepmode': 'backward'},
                                                      {'step': 'all'}])},
                   'rangeslider': {'visible': True}, 'type': 'date'},
             yaxis={"title":"Price (USD)"})}
    return figure


@app.callback(Output('volume', 'figure'),
              [Input('my-dropdown2', 'value')])
def update_graph(selected_dropdown_value):
    dropdown = {"TSLA": "Tesla","AAPL": "Apple","FB": "Facebook","MSFT": "Microsoft",}
    trace1 = []
    for stock in selected_dropdown_value:
        trace1.append(
          go.Scatter(x=df[df["Stock"] == stock]["Date"],
                     y=df[df["Stock"] == stock]["Volume"],
                     mode='lines', opacity=0.7,
                     name=f'Volume {dropdown[stock]}', textposition='bottom center'))
    traces = [trace1]
    data = [val for sublist in traces for val in sublist]
    figure = {'data': data, 
              'layout': go.Layout(colorway=["#5E0DAC", '#FF4F00', '#375CB1', 
                                            '#FF7400', '#FFF400', '#FF0056'],
            height=600,
            title=f"Market Volume for Over Time",
            xaxis={"title":"Date",
                   'rangeselector': {'buttons': list([{'count': 1, 'label': '1M', 
                                                       'step': 'month', 
                                                       'stepmode': 'backward'},
                                                      {'count': 6, 'label': '6M',
                                                       'step': 'month', 
                                                       'stepmode': 'backward'},
                                                      {'step': 'all'}])},
                   'rangeslider': {'visible': True}, 'type': 'date'},
             yaxis={"title":"Transactions Volume"})}
    return figure


@app.callback(
    dash.dependencies.Output('my-graph2', 'figure'),
    [dash.dependencies.Input('feature-selected1', 'value')])
def update_graph(selected_feature1):
    if selected_feature1 == None:
        selected_feature1 = 'Type'
        trace = go.Histogram(x= df2.Type,
                             marker=dict(color='rgb(0, 0, 100)'))
    else:
        trace = go.Histogram(x=df2[selected_feature1],
                         marker=dict(color='rgb(0, 0, 100)'))

    return {
        'data': [trace],
        'layout': go.Layout(title=f'Metrics considered: {selected_feature1.title()}',
                            colorway=["#EF963B", "#EF533B"], hovermode="closest",
                            xaxis={'title': "Distribution", 
                                   'titlefont': {'color': 'black', 'size': 14},
                                   'tickfont': {'size': 14, 'color': 'black'}},
                            yaxis={'title': "Frequency", 
                                   'titlefont': {'color': 'black', 'size': 14, },
                                   'tickfont': {'color': 'black'}})}

Running on http://127.0.0.1:8050/
Debugger PIN: 841-686-022
 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on

SystemExit: 1

C:\Users\User\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2971: UserWarning:

To exit: use 'exit', 'quit', or Ctrl-D.